theme: jekyll-theme-slate
title: The homepage of WANG junhao, hokkaido university student
description: What you will find here are links to projects, publications, and repositories related to the former.
plugins:
  - jemoji
url: "https://JUNHAO0713.github.io/"
markdown: kramdown
